// Generates projects/kavita-ng/i18n/src/langs.ts from the language files next to en.json
//   node scripts/i18n.mjs                   write langs.ts
//   node scripts/i18n.mjs --check           fail if langs.ts is stale or a language has keys en.json does not
//   node scripts/i18n.mjs --import <dir>    copy the keys en.json owns out of Kavita's assets/langs/*.json, then write langs.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const i18nDir = join(root, 'projects/kavita-ng/i18n/src');
const langDir = join(i18nDir, 'lang');
const outputPath = join(i18nDir, 'langs.ts');

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));
const en = readJson(join(langDir, 'en.json'));

// Keeps only the keys en.json has, dropping empty strings so the English fallback applies
function pick(source, shape) {
  const result = {};
  for (const [key, value] of Object.entries(shape)) {
    const found = source?.[key];
    if (typeof value === 'string') {
      if (typeof found === 'string' && found !== '') result[key] = found;
    } else {
      const nested = pick(found, value);
      if (Object.keys(nested).length) result[key] = nested;
    }
  }
  return result;
}

function strayKeys(dictionary, shape, prefix = '') {
  return Object.entries(dictionary).flatMap(([key, value]) => {
    const path = prefix + key;
    if (!(key in shape)) return [path];
    if (typeof value === 'object') return strayKeys(value, shape[key], path + '.');
    return [];
  });
}

const languages = () =>
  readdirSync(langDir)
    .filter((f) => f.endsWith('.json') && f !== 'en.json')
    .map((f) => basename(f, '.json'))
    .sort();

function generate() {
  const entries = languages()
    .map(
      (lang) =>
        `  ${/^[a-z_]\w*$/i.test(lang) ? lang : `'${lang}'`}: () => import('./lang/${lang}.json').then((m) => m.default),`,
    )
    .join('\n');
  return `// Generated by scripts/i18n.mjs from lang/*.json. Run \`npm run i18n\` after adding a language

import { KngDictionary } from './translator';

export const KNG_LANGS: Record<string, () => Promise<KngDictionary>> = {
${entries}
};
`;
}

const args = process.argv.slice(2);

if (args.includes('--import')) {
  const sourceDir = args[args.indexOf('--import') + 1];
  if (!sourceDir || !existsSync(sourceDir)) {
    console.error('Pass the Kavita langs folder: --import <Kavita>/UI/Web/src/assets/langs');
    process.exit(1);
  }
  for (const file of readdirSync(sourceDir).filter((f) => f.endsWith('.json') && f !== 'en.json')) {
    const picked = pick(readJson(join(sourceDir, file)), en);
    if (!Object.keys(picked).length) continue;
    writeFileSync(join(langDir, file), JSON.stringify(picked, null, 2) + '\n');
  }
  writeFileSync(outputPath, generate());
  console.log(`Imported ${languages().length} languages into ${langDir}`);
} else if (args.includes('--check')) {
  const errors = [];
  if (readFileSync(outputPath, 'utf8').replace(/\r\n/g, '\n') !== generate()) {
    errors.push('langs.ts is out of date. Run `npm run i18n` and commit the result');
  }
  for (const lang of languages()) {
    for (const key of strayKeys(readJson(join(langDir, `${lang}.json`)), en)) {
      errors.push(`${lang}.json has ${key}, which en.json does not`);
    }
  }
  if (errors.length) {
    console.error(errors.join('\n'));
    process.exit(1);
  }
  console.log(`i18n ok: ${languages().length} languages besides en`);
} else {
  writeFileSync(outputPath, generate());
  console.log(`Wrote ${outputPath} (${languages().length} languages)`);
}
