// Generates projects/kavita-ng/styles/_tokens.scss from tokens.json
//   node scripts/tokens.mjs           write _tokens.scss
//   node scripts/tokens.mjs --check   fail if _tokens.scss is stale or the compiled styles use a non --kng-/--bs- variable
//   node scripts/tokens.mjs --kavita  print the body mapping block for Kavita
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sass from 'sass';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const stylesDir = join(root, 'projects/kavita-ng/styles');
const manifestPath = join(stylesDir, 'tokens.json');
const outputPath = join(stylesDir, '_tokens.scss');

const tokens = JSON.parse(readFileSync(manifestPath, 'utf8')).groups.flatMap((g) => g.tokens);
const byName = new Map();
const errors = [];

for (const token of tokens) {
  if (byName.has(token.name)) errors.push(`Duplicate token: ${token.name}`);
  byName.set(token.name, token);
}

const parentOf = (token) =>
  typeof token.value === 'string' && token.value.startsWith('@') ? token.value.slice(1) : null;

for (const token of tokens) {
  const seen = new Set([token.name]);
  let parent = parentOf(token);
  while (parent) {
    if (!byName.has(parent)) {
      errors.push(`${token.name} derives from unknown token ${parent}`);
      break;
    }
    if (seen.has(parent)) {
      errors.push(`${token.name} has a derivation cycle through ${parent}`);
      break;
    }
    seen.add(parent);
    parent = parentOf(byName.get(parent));
  }
}

if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

const sassMapEntries = tokens
  .map((t) => `  '${t.name}': ${parentOf(t) ? `'${parentOf(t)}'` : 'null'},`)
  .join('\n');
const rootDeclarations = tokens
  .filter((t) => t.value !== null && !parentOf(t))
  .map((t) => `  --kng-${t.name}: ${t.value};`)
  .join('\n');

const generated = `// Generated by scripts/tokens.mjs from tokens.json. Edit tokens.json and run \`npm run tokens\`

// Token name to the token it derives from, or null for a base token
$tokens: (
${sassMapEntries}
);

@mixin root-defaults {
${rootDeclarations}
}
`;

const args = process.argv.slice(2);

if (args.includes('--kavita')) {
  const lines = tokens
    .filter((t) => t.kavita !== false)
    .map((t) => `  --kng-${t.name}: var(${t.kavita ?? `--${t.name}`});`);
  console.log(`body {\n${lines.join('\n')}\n}`);
} else if (args.includes('--check')) {
  const current = readFileSync(outputPath, 'utf8').replace(/\r\n/g, '\n');
  if (current !== generated) {
    console.error('_tokens.scss is out of date. Run `npm run tokens` and commit the result');
    process.exit(1);
  }

  const css = sass.compile(join(stylesDir, '_index.scss'), { style: 'expanded' }).css;
  const stray = [...new Set(css.match(/var\(--(?!kng-|bs-)[\w-]+/g) ?? [])];
  if (stray.length) {
    console.error(`Compiled styles use variables outside --kng-*/--bs-*:\n${stray.join('\n')}`);
    process.exit(1);
  }
  console.log(`tokens ok: ${tokens.length} tokens, compiled styles only use --kng-* and --bs-*`);
} else {
  writeFileSync(outputPath, generated);
  console.log(`Wrote ${outputPath} (${tokens.length} tokens)`);
}
