// Generated by scripts/i18n.mjs from lang/*.json. Run `npm run i18n` after adding a language

import { KngDictionary } from './translator';

export const KNG_LANGS: Record<string, () => Promise<KngDictionary>> = {
  ca: () => import('./lang/ca.json').then((m) => m.default),
  cs: () => import('./lang/cs.json').then((m) => m.default),
  da: () => import('./lang/da.json').then((m) => m.default),
  de: () => import('./lang/de.json').then((m) => m.default),
  es: () => import('./lang/es.json').then((m) => m.default),
  fr: () => import('./lang/fr.json').then((m) => m.default),
  ga: () => import('./lang/ga.json').then((m) => m.default),
  hu: () => import('./lang/hu.json').then((m) => m.default),
  it: () => import('./lang/it.json').then((m) => m.default),
  ja: () => import('./lang/ja.json').then((m) => m.default),
  ko: () => import('./lang/ko.json').then((m) => m.default),
  nl: () => import('./lang/nl.json').then((m) => m.default),
  pl: () => import('./lang/pl.json').then((m) => m.default),
  pt: () => import('./lang/pt.json').then((m) => m.default),
  pt_BR: () => import('./lang/pt_BR.json').then((m) => m.default),
  pt_PT: () => import('./lang/pt_PT.json').then((m) => m.default),
  ru: () => import('./lang/ru.json').then((m) => m.default),
  sk: () => import('./lang/sk.json').then((m) => m.default),
  sv: () => import('./lang/sv.json').then((m) => m.default),
  ta: () => import('./lang/ta.json').then((m) => m.default),
  th: () => import('./lang/th.json').then((m) => m.default),
  tr: () => import('./lang/tr.json').then((m) => m.default),
  uk: () => import('./lang/uk.json').then((m) => m.default),
  vi: () => import('./lang/vi.json').then((m) => m.default),
  zh_Hans: () => import('./lang/zh_Hans.json').then((m) => m.default),
  zh_Hant: () => import('./lang/zh_Hant.json').then((m) => m.default),
};
